### ISSUE TITLE
Interconnect latency setup

### ISSUE THREAD

**Issue by getianao** [csl-iisc/mgvm#1]
Hi, thanks for the great work. I've been trying to reproduce the results in your paper using your code, but I've run into an issue with the setup value of the interconnect latency: In the paper, the latency is 32ns (32 cycles when the frequency is 1 GHz),  but in the code, it's 360 cycles.

https://github.com/csl-iisc/MGVM-MICRO2022/blob/fd57e792f57666a8f23a172915e5175255aee10f/mgpusim/builders/common.go#L946

Is it the right place to define the interconnect latency? Or it's a typo?

**Comment by PratheekB** [comment]
Hello,

Internally, the network components are wired to tick 12 times per cycles.
With switch latency of 360, every cycle ticking 12 times, we get 30 cycles. In addition, the network components take an additional two cycles.

**Comment by getianao** [comment]
Could you please tell me where in the code the additional two cycles of latency for the network components are defined?

**Comment by PratheekB** [comment]
They are not explicitly defined. We measured the timestamps at sending and receiving components and determined that two cycles are additional used by the intermediate components, like packet buffers.

The following is the starting point for the networking code.
https://github.com/csl-iisc/MGVM-MICRO2022/blob/main/noc/networking/chipnetwork/interchipnetwork.go

Note: we modelled it based on the PCIe network from the original repository, things have changed upstream, please take a look ( https://gitlab.com/akita/noc ).

**Comment by getianao** [comment]
Thank you very much.
